[[manager.prepend_keymap]]
on  = "i"
run = "arrow -1"
desc = "Move cursor up"

[[manager.prepend_keymap]]
on  = "k"
run = "arrow 1"
desc = "Move cursor down"

[[manager.prepend_keymap]]
on  = "j"
run = "leave"
desc = "Go back to the parent directory"

[[manager.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on   = "<Right>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on  = "F"
run = "plugin smart-filter"
desc = "Smart filter"

[[manager.prepend_keymap]]
on  = "M"
run = "plugin mount"
desc = "Mount manager"

[[manager.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block'
desc = "Open shell here"